"""
Code Deliverable Artifact Generator for MRPL AI Workbench.
Generates verified code deliverables.
"""

from pathlib import Path


def generate_code_artifact(
    output_path: Path,
    task_id: str,
    code_content: str,
    language: str = "python",
) -> Path:
    """
    Writes a verified code artifact file to disk.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        f"# ====================================================\n"
        f"# MRPL AI WORKBENCH — VERIFIED CODE DELIVERABLE\n"
        f"# Task ID: {task_id}\n"
        f"# Language: {language}\n"
        f"# GENERATED BY MRPL AI WORKBENCH — DEMONSTRATION\n"
        f"# ====================================================\n\n"
    )
    full_content = header + code_content
    output_path.write_text(full_content, encoding="utf-8")
    return output_path
