"""
DOCX Document Generator for MRPL AI Workbench.
Generates structured .docx Approval Notes for industrial workflows.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional
import os


def generate_docx_approval_note(
    output_path: Path,
    task_id: str,
    title: str = "MRPL AI WORKBENCH — OFFICIAL APPROVAL NOTE",
    reference_number: str = "MRPL-AI-DEMO-001",
    subject: str = "Inspection Findings & Recommended Maintenance Actions",
    background: str = "Automated inspection analysis conducted via MRPL Sovereign On-Premise AI Workbench.",
    findings: Optional[List[str]] = None,
    sources: Optional[List[Dict[str, Any]]] = None,
    recommendations: Optional[List[str]] = None,
    approver: str = "Chief Technical Inspector",
    approval_status: str = "APPROVED",
) -> Path:
    """
    Generates a structured .docx Approval Note.
    Uses `docx` library if available, otherwise writes formatted structured deliverable.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    findings = findings or ["No critical structural anomalies detected.", "All pressure thresholds operating within normal limits."]
    recommendations = recommendations or ["Schedule routine quarterly inspection.", "Update maintenance log in central database."]
    sources = sources or []

    try:
        import docx
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = docx.Document()

        # Title
        p_title = doc.add_paragraph()
        p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run_title = p_title.add_run(title)
        run_title.bold = True
        run_title.font.size = Pt(16)
        run_title.font.color.rgb = RGBColor(0, 51, 102)

        # Header Info Table / Paragraphs
        p_meta = doc.add_paragraph()
        p_meta.add_run(f"Reference Number: ").bold = True
        p_meta.add_run(f"{reference_number}\n")
        p_meta.add_run(f"Task ID: ").bold = True
        p_meta.add_run(f"{task_id}\n")
        p_meta.add_run(f"Subject: ").bold = True
        p_meta.add_run(f"{subject}\n")

        doc.add_heading("1. Background & Context", level=2)
        doc.add_paragraph(background)

        doc.add_heading("2. Key Findings & Observations", level=2)
        for finding in findings:
            doc.add_paragraph(f"• {finding}")

        if sources:
            doc.add_heading("3. Reference Evidence & Sources", level=2)
            for src in sources:
                doc_name = src.get("source", "Document")
                text_snippet = src.get("text", "")
                doc.add_paragraph(f"• Source: {doc_name}\n  Snippet: {text_snippet[:200]}")

        doc.add_heading("4. Recommendations", level=2)
        for rec in recommendations:
            doc.add_paragraph(f"• {rec}")

        doc.add_heading("5. Approval Governance Section", level=2)
        p_app = doc.add_paragraph()
        p_app.add_run(f"Approver Role: ").bold = True
        p_app.add_run(f"{approver}\n")
        p_app.add_run(f"Approval Status: ").bold = True
        p_app.add_run(f"{approval_status}\n")

        p_footer = doc.add_paragraph()
        p_footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run_foot = p_footer.add_run("\n--- GENERATED BY MRPL AI WORKBENCH — DEMONSTRATION ---")
        run_foot.font.size = Pt(9)
        run_foot.font.italic = True
        run_foot.font.color.rgb = RGBColor(128, 128, 128)

        doc.save(str(output_path))
    except Exception:
        # Fallback to plain text document if python-docx fails
        content = (
            f"{title}\n"
            f"====================================================\n"
            f"Reference Number: {reference_number}\n"
            f"Task ID: {task_id}\n"
            f"Subject: {subject}\n\n"
            f"1. BACKGROUND & CONTEXT\n"
            f"{background}\n\n"
            f"2. KEY FINDINGS\n"
            + "\n".join(f" - {f}" for f in findings) + "\n\n"
            f"3. RECOMMENDATIONS\n"
            + "\n".join(f" - {r}" for r in recommendations) + "\n\n"
            f"4. APPROVAL GOVERNANCE\n"
            f"Approver: {approver}\n"
            f"Status: {approval_status}\n\n"
            f"--- GENERATED BY MRPL AI WORKBENCH — DEMONSTRATION ---\n"
        )
        output_path.write_text(content, encoding="utf-8")

    return output_path
