"""
Artifact Data Models for MRPL AI Workbench.
Defines schemas and metadata structures for generated local deliverables.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


class ArtifactType(str, Enum):
    DOCX = "docx"
    XLSX = "xlsx"
    PPTX = "pptx"
    TXT = "txt"
    MD = "md"
    CODE = "code"


class ArtifactMetadata(BaseModel):
    """
    Metadata representation for an artifact produced by the workbench.
    """
    artifact_id: str = Field(..., description="Unique UUID or identifier for the artifact")
    task_id: str = Field(..., description="Associated agent task ID")
    filename: str = Field(..., description="Target deliverable filename")
    artifact_type: ArtifactType = Field(..., description="Artifact category type")
    filepath: str = Field(..., description="Absolute local filesystem path to generated artifact")
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 creation timestamp",
    )
    size_bytes: int = Field(0, description="Size of generated file in bytes")
    watermark: str = Field(
        "GENERATED BY MRPL AI WORKBENCH — DEMONSTRATION",
        description="Air-gapped enterprise sovereignty watermark",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Custom payload metadata (e.g. title, reference_number, subject, findings)",
    )
