"""
PPTX Presentation Artifact Generator for MRPL AI Workbench.
Generates structured PowerPoint presentation summaries.
"""

from pathlib import Path
from typing import List, Optional


def generate_pptx_artifact(
    output_path: Path,
    task_id: str,
    title: str = "MRPL AI WORKBENCH — EXECUTIVE SUMMARY",
    slides_content: Optional[List[Dict[str, Any]]] = None,
) -> Path:
    """
    Generates a structured .pptx presentation file.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    slides_content = slides_content or [
        {
            "title": "Inspection Executive Summary",
            "bullets": [
                "Refinery Unit 4 Inspection Complete",
                "Compliance verified against SOP MRPL-AI-DEMO-001",
                "No critical anomalies found",
            ],
        },
        {
            "title": "Approval & Governance",
            "bullets": [
                f"Task ID: {task_id}",
                "Status: APPROVED",
                "Air-Gapped Sovereign Execution Verified",
            ],
        },
    ]

    try:
        from pptx import Presentation

        prs = Presentation()

        # Title slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        slide.placeholders[1].text = f"Task ID: {task_id}\nGENERATED BY MRPL AI WORKBENCH — DEMONSTRATION"

        # Content slides
        bullet_slide_layout = prs.slide_layouts[1]
        for s_data in slides_content:
            c_slide = prs.slides.add_slide(bullet_slide_layout)
            c_slide.shapes.title.text = s_data.get("title", "Slide")
            tf = c_slide.placeholders[1].text_frame
            for idx, bullet in enumerate(s_data.get("bullets", [])):
                if idx == 0:
                    tf.text = bullet
                else:
                    p = tf.add_paragraph()
                    p.text = bullet

        prs.save(str(output_path))
    except Exception:
        # Fallback to markdown presentation format
        lines = [f"# {title}", f"Task ID: {task_id}\n"]
        for s_data in slides_content:
            lines.append(f"## {s_data.get('title', 'Slide')}")
            for b in s_data.get("bullets", []):
                lines.append(f"- {b}")
            lines.append("")
        lines.append("--- GENERATED BY MRPL AI WORKBENCH — DEMONSTRATION ---")
        output_path.write_text("\n".join(lines), encoding="utf-8")

    return output_path
