"""
XLSX Spreadsheet Artifact Generator for MRPL AI Workbench.
Generates structured tabular deliverables for inspection & audit reports.
"""

from pathlib import Path
from typing import Any, Dict, List


def generate_xlsx_artifact(
    output_path: Path,
    task_id: str,
    title: str = "MRPL AI WORKBENCH — TABULAR DELIVERABLE",
    headers: Optional[List[str]] = None,
    rows: Optional[List[List[Any]]] = None,
) -> Path:
    """
    Generates a structured .xlsx spreadsheet.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    headers = headers or ["Item ID", "Parameter / Metric", "Observed Value", "Status", "Remarks"]
    rows = rows or [
        ["1", "Operating Pressure", "12.4 bar", "PASS", "Within safe operating limit"],
        ["2", "Wall Thickness", "14.2 mm", "PASS", "Zero corrosion detected"],
        ["3", "Inspection Status", "Verified", "APPROVED", "MRPL-AI-DEMO-001 compliant"],
    ]

    try:
        import openpyxl

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Workbench Deliverable"

        ws.append([title])
        ws.append([f"Task ID: {task_id}"])
        ws.append([])  # Blank row
        ws.append(headers)

        for row in rows:
            ws.append(row)

        ws.append([])
        ws.append(["GENERATED BY MRPL AI WORKBENCH — DEMONSTRATION"])

        wb.save(str(output_path))
    except Exception:
        # Fallback to CSV format if openpyxl unavailable
        lines = [f"# {title}", f"# Task ID: {task_id}", ",".join(headers)]
        for row in rows:
            lines.append(",".join(str(cell) for cell in row))
        lines.append("# GENERATED BY MRPL AI WORKBENCH — DEMONSTRATION")
        output_path.write_text("\n".join(lines), encoding="utf-8")

    return output_path
