"""
Local RAG request, response, and source citation Pydantic schema models.
"""

from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field

from src.schemas.document import DocumentChunkSchema


class SourceCitationSchema(BaseModel):
    """
    Source metadata citation payload linking answer statements to source document chunks.
    """

    document_id: str = Field(..., description="Unique document identifier")
    filename: str = Field(..., description="Original filename of source document")
    page: Optional[int] = Field(default=None, description="Page or sheet number if available")
    chunk_id: Union[int, str] = Field(..., description="Chunk sequence index or ID")
    file_hash: Optional[str] = Field(default=None, description="SHA-256 hash digest")
    score: Optional[float] = Field(default=None, description="Similarity search relevance score")
    snippet: Optional[str] = Field(default=None, description="Brief text snippet excerpt")


class RAGIndexRequest(BaseModel):
    """Payload for POST /documents/index request."""

    document_id: Optional[str] = Field(default=None, description="Optional document ID override")
    filename: str = Field(..., description="Original file name")
    file_hash: str = Field(..., description="SHA-256 hash digest of document content")
    file_extension: Optional[str] = Field(default=None, description="File extension (e.g. .pdf)")
    chunks: List[DocumentChunkSchema] = Field(..., description="List of text chunks from Phase 5 pipeline")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional document metadata specs")


class RAGIndexResponse(BaseModel):
    """Response model for POST /documents/index."""

    status: str = Field(default="SUCCESS", description="Indexing status indicator")
    document_id: str = Field(..., description="Assigned unique document ID")
    filename: str = Field(..., description="Original filename")
    indexed_chunks_count: int = Field(..., description="Total chunks indexed into vector store")
    message: str = Field(default="Document indexed successfully", description="Status detail message")


class RAGQueryRequest(BaseModel):
    """Payload for POST /documents/query request."""

    query: str = Field(..., description="User prompt or question text", min_length=1)
    top_k: Optional[int] = Field(default=None, description="Optional top_k chunks retrieval limit", ge=1, le=20)
    collection_name: Optional[str] = Field(default=None, description="Optional target vector collection override")


class RAGQueryResponse(BaseModel):
    """Response model for POST /documents/query."""

    answer: str = Field(..., description="Grounded response text generated by Qwen LLM")
    sources: List[SourceCitationSchema] = Field(default_factory=list, description="Source metadata citations")
    query: str = Field(..., description="Original query string")
    model_used: str = Field(default="qwen2.5:7b", description="Identifier of LLM used for grounding")
    tokens_generated: int = Field(default=0, description="Estimated tokens generated in answer")
    execution_time_seconds: float = Field(default=0.0, description="Total RAG execution time in seconds")
    status: str = Field(default="SUCCESS", description="Query execution status")


class RAGHealthResponse(BaseModel):
    """Response model for GET /documents/rag/health."""

    status: str = Field(default="healthy", description="RAG subsystem operational status")
    rag_enabled: bool = Field(default=True, description="RAG subsystem toggle setting")
    collection_name: str = Field(..., description="Target vector store collection name")
    total_chunks_indexed: int = Field(default=0, description="Total vectors currently stored in collection")
    embedding_provider: Dict[str, Any] = Field(default_factory=dict, description="Embedding provider status")
    vector_store: Dict[str, Any] = Field(default_factory=dict, description="Vector store health details")
