# ====================================================
# MRPL AI WORKBENCH — VERIFIED CODE DELIVERABLE
# Task ID: task-code-6e54fce7
# Language: python
# GENERATED BY MRPL AI WORKBENCH — DEMONSTRATION
# ====================================================

import re

def validate_mrpl_email(email: str) -> bool:
    """Validates MRPL enterprise email address pattern (user@mrpl.co.in or user@mrpl.in)."""
    if not isinstance(email, str):
        return False
    pattern = r'^[a-zA-Z0-9._%+-]+@mrpl\.(co\.in|in)$'
    return bool(re.match(pattern, email.strip()))

# Test cases
assert validate_mrpl_email('operator@mrpl.co.in') is True
assert validate_mrpl_email('inspector@mrpl.in') is True
assert validate_mrpl_email('external@gmail.com') is False
