"""
RAG REST API Routes for MRPL AI Workbench.
Exposes endpoints for document vector indexing, grounded query execution, deletion, and health.
"""

from typing import Annotated, Dict
from fastapi import APIRouter, Depends, HTTPException, Path

from src.api.dependencies import get_rag_service
from src.api.responses.standard_response import StandardResponse, success_response
from src.rag.rag_service import RAGService
from src.schemas.rag import (
    RAGHealthResponse,
    RAGIndexRequest,
    RAGIndexResponse,
    RAGQueryRequest,
    RAGQueryResponse,
)

router = APIRouter(tags=["RAG Knowledge Base"])


@router.post(
    "/documents/index",
    response_model=StandardResponse[RAGIndexResponse],
    summary="Index Processed Document Chunks into Vector Store",
    description="Index text chunks generated by Phase 5 pipeline into local persistent vector store for RAG retrieval.",
)
async def index_document(
    request: RAGIndexRequest,
    rag_service: Annotated[RAGService, Depends(get_rag_service)],
) -> StandardResponse[RAGIndexResponse]:
    """
    POST /documents/index endpoint indexing document chunks.
    """
    try:
        res_dict = rag_service.index_document(
            filename=request.filename,
            file_hash=request.file_hash,
            chunks=request.chunks,
            document_id=request.document_id,
            file_extension=request.file_extension,
            metadata=request.metadata,
        )

        response_payload = RAGIndexResponse(
            status=res_dict.get("status", "SUCCESS"),
            document_id=res_dict["document_id"],
            filename=res_dict["filename"],
            indexed_chunks_count=res_dict["indexed_chunks_count"],
            message=res_dict["message"],
        )

        return success_response(
            data=response_payload,
            message=f"Document '{request.filename}' indexed successfully into vector store.",
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Indexing failed: {str(exc)}")


@router.post(
    "/documents/query",
    response_model=StandardResponse[RAGQueryResponse],
    summary="Query Grounded RAG Document Knowledge Base",
    description="Retrieve relevant document vector chunks and generate grounded answer with source citations using Qwen 2.5 7B.",
)
async def query_rag(
    request: RAGQueryRequest,
    rag_service: Annotated[RAGService, Depends(get_rag_service)],
) -> StandardResponse[RAGQueryResponse]:
    """
    POST /documents/query endpoint executing grounded RAG retrieval and synthesis.
    """
    try:
        rag_response = await rag_service.query(
            query=request.query,
            top_k=request.top_k,
            collection_name=request.collection_name,
        )

        return success_response(
            data=rag_response,
            message="RAG query executed successfully",
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"RAG query execution failed: {str(exc)}")


@router.delete(
    "/documents/{document_id}",
    response_model=StandardResponse[Dict[str, int]],
    summary="Delete Document from RAG Vector Store",
    description="Purge all indexed vector chunks belonging to a document_id from local vector store.",
)
async def delete_document(
    document_id: str = Path(..., description="Target document ID to delete"),
    rag_service: RAGService = Depends(get_rag_service),
) -> StandardResponse[Dict[str, int]]:
    """
    DELETE /documents/{document_id} endpoint purging document vectors.
    """
    try:
        deleted_chunks = rag_service.delete_document(document_id=document_id)
        return success_response(
            data={"deleted_chunks_count": deleted_chunks},
            message=f"Purged {deleted_chunks} vector chunks for document_id '{document_id}'.",
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Document deletion failed: {str(exc)}")


@router.get(
    "/documents/rag/health",
    response_model=StandardResponse[RAGHealthResponse],
    summary="RAG Subsystem Health Check",
    description="Retrieve local vector store status, embedding provider health, and indexed chunk count.",
)
async def get_rag_health(
    rag_service: Annotated[RAGService, Depends(get_rag_service)],
) -> StandardResponse[RAGHealthResponse]:
    """
    GET /documents/rag/health endpoint returning RAG metrics.
    """
    health_dict = rag_service.health()

    health_payload = RAGHealthResponse(
        status=health_dict.get("status", "healthy"),
        rag_enabled=health_dict.get("rag_enabled", True),
        collection_name=health_dict.get("collection_name", "mrpl_documents"),
        total_chunks_indexed=health_dict.get("total_chunks_indexed", 0),
        embedding_provider=health_dict.get("embedding_provider", {}),
        vector_store=health_dict.get("vector_store", {}),
    )

    return success_response(
        data=health_payload,
        message="RAG subsystem operational health metrics retrieved",
    )
